<?php

namespace AppBundle\Repository;

/**
 * MyCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
