<?php

namespace AppBundle\Repository;

/**
 * MyProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyProductRepository extends \Doctrine\ORM\EntityRepository
{
}
