<?php

namespace AppBundle\Repository;

/**
 * UserFriendsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFriendsRepository extends \Doctrine\ORM\EntityRepository
{
    // UserFriends::friend JOIN User::id
    public function findOneByIdJoinedToUser($userId)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT f, u FROM AppBundle:UserFriends f
                JOIN f.friend u
                WHERE f.id = :id'
            )->setParameter('id', $userId);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
