<?php

namespace AppBundle\Repository;

/**
 * UserFriendsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFriendsRepository extends \Doctrine\ORM\EntityRepository
{
}
