
# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # requires the user to be logged in to access this URL(localhost:8000/admin, localhost:8000/login):
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/easyadmin, roles: ROLE_ADMIN }
        - { path: ^/login2, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/user, roles: [ROLE_ADMIN, ROLE_USER]}



    ## https://symfony.com/doc/current/security/entity_provider.html
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        ## https://symfony.com/doc/current/security/entity_provider.html
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

        #in_memory:
        #    memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #the firewall can handle LOUGOUT this automatically for you when you activate the logout config parameter:
        #secured_area:
            # ...
        #    logout:
        #        path:   /logout
        #        target: /

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            form_login:
                login_path: login2
                check_path: login2

            ## https://symfony.com/doc/current/security/entity_provider.html
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider

            #KPNUniversity: https://knpuniversity.com/screencast/symfony-security/authenticator-get-user-check-credentials#play
            #To activate the authenticator, add a new key under your firewall called guard. See services.yml for service-name
            guard:
                authenticators:
                    - app.security.login_form_authenticator
            #Now, if the user goes to /logout, symfony will logging out automatically
            logout:
                path: /logout