# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument:

    #KPNUniversity: https://knpuniversity.com/screencast/symfony-security/authenticator-get-user-check-credentials#play
    #To do that, open up app/config/services.yml and register the authenticator as a service.
    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true

    #https://knpuniversity.com/screencast/symfony-security/encoding-user-password#play
    #Finally, to tell Doctrine about our event subscriber, we'll add a tag
    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    #How to Register Event Listeners and Subscribers
    #http://symfony.com/doc/current/doctrine/event_listeners_subscribers.html
    #incuding: using my own logger in a Service Class
    app.doctrine.my_product_listener:
        class: AppBundle\Doctrine\MyProductListener
        autowire: true
        #arguments: #should be automatically loaded by autowire
        #    - "@logger"
        tags:
            - { name: monolog.logger, channel: acme }
            - { name: doctrine.event_listener, event: postPersist }

    #test: Making the Locale "Sticky" during a User's Session
    #http://symfony.com/doc/current/session/locale_sticky_session.html
    AppBundle\EventSubscriber\LocaleSubscriber:
        arguments: ['%kernel.default_locale%']
        # redundant if you're using autoconfigure
        tags: [kernel.event_subscriber]





